### ISSUE TITLE
department_ids in freshservice_requestor table

### ISSUE THREAD

**Issue by timquinn** [theapsgroup/steampipe-plugin-freshservice#42]
Just a heads up that it looks like the department_ids column is pulling up null in the freshservice_requestor table.

**Comment by graza-io** [comment]
Hi @timquinn - apologies, for some reason I didn't receive a notification from GitHub about this issue being raised...

Just wanted you to know I have confirmed this is a bug & I'll get it resolved ASAP.

**Comment by graza-io** [comment]
Released in `v0.0.3`
